version: '2'

networks:
  zammad:
    driver: bridge

services:

  zammad:
    depends_on:
      - zammad-elasticsearch
      - zammad-postgresql
    image: ffddorf/zammad-docker-compose:zammad
    build:
      context: .
      dockerfile: containers/zammad/Dockerfile
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.start_once: 'true'
    restart: on-failure
    volumes:
      - data-zammad:/home/zammad
    networks:
      zammad:
        aliases:
          - zammad

  zammad-elasticsearch:
    image: ffddorf/zammad-docker-compose:zammad-elasticsearch
    build:
      context: .
      dockerfile: containers/zammad-elasticsearch/Dockerfile
    labels:
      io.rancher.container.pull_image: always
    restart: always
    networks:
      zammad:
        aliases:
          - elasticsearch


  zammad-nginx:
    depends_on:
      - zammad
    image: ffddorf/zammad-docker-compose:zammad-nginx
    build:
      context: .
      dockerfile: containers/zammad-nginx/Dockerfile
    labels:
      io.rancher.container.pull_image: always
    restart: always
    volumes:
      - data-zammad:/home/zammad
    networks:
      zammad:
        aliases:
          - app

  zammad-postgresql:
    image: ffddorf/zammad-docker-compose:zammad-postgresql
    build:
      context: .
      dockerfile: containers/zammad-postgresql/Dockerfile
    labels:
      io.rancher.container.pull_image: always
    restart: always
    networks:
      zammad:
        aliases:
          - postgresql
    volumes:
      - db-zammad:/var/lib/postgresql/data

  zammad-railsserver:
    depends_on:
      - zammad
    image: ffddorf/zammad-docker-compose:zammad-railsserver
    build:
      context: .
      dockerfile: containers/zammad-railsserver/Dockerfile
    labels:
      io.rancher.container.pull_image: always
    depends_on:
      - zammad
    restart: always
    volumes:
      - data-zammad:/home/zammad
    networks:
      zammad:
        aliases:
          - railsserver

  zammad-scheduler:
    depends_on:
      - zammad
    image: ffddorf/zammad-docker-compose:zammad-scheduler
    build:
      context: .
      dockerfile: containers/zammad-scheduler/Dockerfile
    labels:
      io.rancher.container.pull_image: always
    restart: always
    volumes:
      - data-zammad:/home/zammad
    networks:
      zammad:
        aliases:
          - scheduler

  zammad-websocket:
    depends_on:
      - zammad
    image: ffddorf/zammad-docker-compose:zammad-websocket
    build:
      context: .
      dockerfile: containers/zammad-websocket/Dockerfile
    labels:
      io.rancher.container.pull_image: always
    restart: always
    volumes:
      - data-zammad:/home/zammad
    networks:
      zammad:
        aliases:
          - websocket

  zammad-https-nginx:
    depends_on:
      - zammad-nginx
    image: nomaster/nginx
    restart: always
    networks:
      zammad:
        aliases:
          - https-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginx-zammad:/etc/resty-auto-ssl/storage

  smtp:
    depends_on:
      - zammad-postgresql
    image: mraerino/zammad-smtp-receiver
    restart: always
    networks:
      - zammad
    ports:
      - "25:25"

volumes:
  data-zammad:
    driver: local
  db-zammad:
    driver: local
  nginx-zammad:
    driver: local
